name: image-hub

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres_db
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    links:
      - postgres_db
  postgres_db:
      container_name: "postgres-db"
      image: postgres:17-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - "6543:5432"
      environment:
        - POSTGRES_USER=some_db_user
        - POSTGRES_PASSWORD=some#password
        - POSTGRES_DB=image_hub

volumes:
      postgres_data:
